version: '3'
services:
  web:
    build: .
    command: supervisor
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      MONGODB_URI: "mongodb://mongo:27017/base" 
    volumes:
      - ./application:/opt/app
  mongo:
    image: mongo
    ports:
      - 27017:27017